name: Build and push Docker image to Docker Hub on merging to master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: kicsipixel/githubaction:latest
