name: Run Docker Container on Schedule

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  run-docker-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '6.0'
          mongodb-username: ${{ secrets.MONGODB_USER }}
          mongodb-password: ${{ secrets.MONGODB_PWD }}
          mongodb-db: ${{ secrets.MONGODB_DATABASE }}

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Run Docker container
        env:
          MONGODB_PWD: ${{ secrets.MONGODB_PWD }}
          MONGODB_USER: ${{ secrets.MONGODB_USER }}
          MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
        run: |
          docker run --rm \
            -e MONGODB_PWD="${{ secrets.MONGODB_PWD }}" \
            -e MONGODB_USER="${{ secrets.MONGODB_USER }}" \
            -e MONGODB_DATABASE="${{ secrets.MONGODB_DATABASE }}" \
            julienhae/alpinescraper:latest
