name: Run Docker Container on Schedule

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

env:
  MONGODB_PWD: ${{ secrets.MONGODB_PWD }}
  MONGODB_USER: ${{ secrets.MONGODB_USER }}
  MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
  DOCKER_ARGS: --collection_name TESTBIS --nb_spider 25 --scraper acmimmobilier

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

  run-docker-container:
    needs: set-env
    runs-on: ubuntu-latest

    steps:
      - name: Run Docker container
        run: |
          docker run --rm \
            -e MONGODB_PWD="${{ secrets.MONGODB_PWD }}" \
            -e MONGODB_USER="${{ secrets.MONGODB_USER }}" \
            -e MONGODB_DATABASE="${{ secrets.MONGODB_DATABASE }}" \
            julienhae/alpinescraper:latest main_mongodb ${{ env.DOCKER_ARGS }}
