name: ci

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Print env variables
        run: env
      - name: Username
        run: echo "Username '${{ vars.DOCKERHUB_USERNAME }}'"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
