name: Run Alpinescraper on Schedule

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

env:
  MONGODB_PWD: ${{ secrets.MONGODB_PWD }}
  MONGODB_USER: ${{ secrets.MONGODB_USER }}
  MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
  AGENCEOLIVIER_ARGS: --collection_name AGENCEOLIVIER --nb_spider 10 --scraper agenceolivier --append
  ACMIMMOBILIER_ARGS: --collection_name ACMIMMOBILIER --nb_spider 15 --scraper acmimmobilier --append
  ASCENSIONIMMO_ARGS: --collection_name ASCENSIONIMMO --nb_spider 15 --scraper ascensionimmo --append
  MORZINEIMMO_ARGS: --collection_name MORZINEIMMO --nb_spider 5 --scraper morzineimmo --append

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

  alpinescrape-agenceolivier:
    needs: set-env
    runs-on: ubuntu-latest

    steps:
      - name: Scrape Agence Olivier
        run: |
          docker run --rm \
            -e MONGODB_PWD="${{ secrets.MONGODB_PWD }}" \
            -e MONGODB_USER="${{ secrets.MONGODB_USER }}" \
            -e MONGODB_DATABASE="${{ secrets.MONGODB_DATABASE }}" \
            julienhae/alpinescraper:latest main_mongodb ${{ env.AGENCEOLIVIER_ARGS }}

  alpinescrape-acmimmobilier:
    needs: set-env
    runs-on: ubuntu-latest

    steps:
      - name: Scrape ACM Immobilier
        run: |
          docker run --rm \
            -e MONGODB_PWD="${{ secrets.MONGODB_PWD }}" \
            -e MONGODB_USER="${{ secrets.MONGODB_USER }}" \
            -e MONGODB_DATABASE="${{ secrets.MONGODB_DATABASE }}" \
            julienhae/alpinescraper:latest main_mongodb ${{ env.ACMIMMOBILIER_ARGS }}

  alpinescrape-ascensionimmo:
    needs: set-env
    runs-on: ubuntu-latest

    steps:
      - name: Scrape Ascension Immo
        run: |
          docker run --rm \
            -e MONGODB_PWD="${{ secrets.MONGODB_PWD }}" \
            -e MONGODB_USER="${{ secrets.MONGODB_USER }}" \
            -e MONGODB_DATABASE="${{ secrets.MONGODB_DATABASE }}" \
            julienhae/alpinescraper:latest main_mongodb ${{ env.ASCENSIONIMMO_ARGS }}

  alpinescrape-morzineimmo:
    needs: set-env
    runs-on: ubuntu-latest

    steps:
      - name: Scrape Morzine Immo
        run: |
          docker run --rm \
            -e MONGODB_PWD="${{ secrets.MONGODB_PWD }}" \
            -e MONGODB_USER="${{ secrets.MONGODB_USER }}" \
            -e MONGODB_DATABASE="${{ secrets.MONGODB_DATABASE }}" \
            julienhae/alpinescraper:latest main_mongodb ${{ env.MORZINEIMMO_ARGS }}
